[workspace]
members = [
    "jdk_selector_shared",
    "jdk_selector_cli",
    "jdk_selector_executor",
    "jdk_selector_builder",
]

[profile.release]
strip = true # Strip symbols from binary for non-Windows distributions